### ISSUE TITLE
Time delay fickleness

### ISSUE THREAD

**Issue by LoScienzo** [CriticalPoint/Remove-Steam-Guide-Button-Bind---Disable-Big-Picture-Mode#5]
I had to double the task delay to 8 seconds for the unbinding to succeed.
I didn't do much testing besides rebooting and changing the value, but 4 seconds didn't work and 8 did 😁

Thank you for this tool! 🚀🥦

**Comment by CriticalPoint** [comment]
You're so welcome, [LoScienzo](https://github.com/LoScienzo), thanks for showing appreciation! 🤜🏻🤛🏻

Thanks for taking the time to feed that back - I've updated the screenshots for the scheduled task to reflect your findings.

Whilst in there, I also finished and applied another update... The script now automatically finds your Config file, making it path agnostic (the bit I needed to do for non-default installs)

If you find anything else, or have any other feedback, please do let me know! 😇
